apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: argocd
  namespace: argocd  
spec: 
  project: default
  source:
    repoURL: https://github.com/antoniocsjf/aula-argocd.git
    path: argocd
    targetRevision: HEAD
    directory: 
<<<<<<< HEAD
       recurse: true
=======
      recurse: true
>>>>>>> 5541864 (up app 2)
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc

